language: python
python:
  - 2.7
node_js:
  - v6
before_install:
  - python setup.py install
  - pip install coveralls
  - nvm install 6
  - nvm use 6
  - npm install
  - npm run build
script:
  - python tests.py coverage
  - npm run test

