language: python
python:
  - 2.7
install:
  - python setup.py install
  - pip install coveralls
script:
  - python tests.py coverage

language: node_js
node_js:
  - v6
insall:
  - npm install
  - npm run build
script:
  - npm run test
