#CONFIG
DEBUG: False
VERBOSE: False
SQLALCHEMY_TRACK_MODIFICATIONS: False

#FLASK
SECRET_KEY: 'production key'
SECURITY_PASSWORD_SALT: 'production password salt'

WEBPACK_MANIFEST_PATH: './build/manifest.json'